### ISSUE TITLE
Migration dependency

### ISSUE THREAD

**Issue by sekoskel** [andersinno/django-form-designer-ai#16]
form_designer/contrib/cms_plugins/form_designer_form/migrations/0001_initial.py
has `('cms', '0014_auto_20160404_1908'),` does this really mean, that form-designer is not compatible with django cms < 3.3x ?

**Comment by akx** [comment]
Nope. That's probably because I've autogenerated the migration while having "just any" Django CMS version installed.

Will fix it. Thanks for the bug report!

**Comment by akx** [comment]
This was fixed in v0.10.1, now available on [GitHub](https://github.com/andersinno/django-form-designer-ai/releases/tag/v0.10.1) and [PyPI](https://pypi.python.org/pypi/django-form-designer-ai/0.10.1).
